### ISSUE TITLE
ERROR: not all ranks! on -rank_trees

### ISSUE THREAD

**Issue by MaoYafei** [anastasiiakim/ranked-coal#2] opened 2020-02-06 00:19 UTC
Hi All,

I am trying to run pranc but I found that I have some issues on running. Could you help me to figure them out?

#test examples:

> $ cat unrgt_5taxon.txt 
> ((B,E),(A,(C,D)));
> $ pranc -rank_trees unrgt_5taxon.txt 
> $ cat outRankTopos.txt 
> ((B:3,E:3):1,(A:2,(C:1,D:1):1):2);
> ((B:2,E:2):2,(A:3,(C:1,D:1):2):1);
> ((B:1,E:1):3,(A:3,(C:2,D:2):1):1);

#my data

> cat treedist_1.txt 
> (Orangutan,(HMO,(NLE,(SSY,HLE))));
> $ pranc -rank_trees treedist_1.txt 
> ERROR: not all ranks!

Is there something wrong with my tree?

Thank you so much.

Best, 
Yafei

**Comment by anastasiiakim** [comment] 2020-02-06 19:52
PRANC didn't know how to work with the long taxa names for -rank_trees. The issue is now fixed. The output looks like this: (Orangutan:4,(HMO:3,(NLE:2,(SSY:1,HLE:1):1):1):1);

**Closed as completed** 2020-02-06 19:52 UTC
